import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Each project under docs/<project>/ gets one top-level category here, built from
 * autogenerated subtrees so individual pages never need a sidebar entry of their own.
 * Adding another project means adding its own top-level category the same way core's
 * and udon-test-kit's are built below, not relying on blanket autogeneration (see
 * AGENTS.md's Gotchas section for why).
 *
 * Each labeled category below wraps a single-folder `autogenerated` subtree: pointing
 * `dirName` straight at a leaf folder returns its files as a flat list with no label of
 * its own, so the folder's `_category_.json` label is repeated here explicitly to give
 * that flat list a heading.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Core',
      link: {type: 'doc', id: 'core/intro'},
      items: [
        {
          type: 'category',
          label: 'Getting started',
          items: ['core/add-to-your-project', 'core/first-behaviour'],
        },
        {
          type: 'category',
          label: 'How-to guides',
          items: [{type: 'autogenerated', dirName: 'core/how-to'}],
        },
        {
          type: 'category',
          label: 'Reference',
          items: [
            {
              type: 'category',
              label: 'Core concepts',
              items: [{type: 'autogenerated', dirName: 'core/core-concepts'}],
            },
            {
              type: 'category',
              label: 'Players & tracking',
              items: [{type: 'autogenerated', dirName: 'core/players-tracking'}],
            },
            {
              type: 'category',
              label: 'Networking & data',
              items: [
                'core/networking-data/tsvrc-memory',
                'core/networking-data/tsvrc-timer',
                {
                  type: 'category',
                  label: 'Data transfer chain',
                  link: {type: 'doc', id: 'core/networking-data/data-transfer-overview'},
                  items: [{type: 'autogenerated', dirName: 'core/networking-data/data-transfer'}],
                },
              ],
            },
            {
              type: 'category',
              label: 'UI components',
              items: [
                {
                  type: 'category',
                  label: 'List',
                  items: [{type: 'autogenerated', dirName: 'core/ui-components/list'}],
                },
                'core/ui-components/texture-graphics-2d',
                {
                  type: 'category',
                  label: 'Player position overlay',
                  items: [{type: 'autogenerated', dirName: 'core/ui-components/overlay'}],
                },
              ],
            },
            {
              type: 'category',
              label: 'Game flow',
              items: [{type: 'autogenerated', dirName: 'core/game-flow'}],
            },
            {
              type: 'category',
              label: 'Utilities',
              items: [{type: 'autogenerated', dirName: 'core/utilities'}],
            },
            {
              type: 'category',
              label: 'Codegen',
              items: [
                {
                  type: 'category',
                  label: 'Config',
                  items: [{type: 'autogenerated', dirName: 'core/codegen/config'}],
                },
                {
                  type: 'category',
                  label: 'Modules',
                  items: [{type: 'autogenerated', dirName: 'core/codegen/modules'}],
                },
                {
                  type: 'category',
                  label: 'Internals',
                  items: [{type: 'autogenerated', dirName: 'core/codegen/internals'}],
                },
              ],
            },
            {
              type: 'category',
              label: 'Testing',
              items: [{type: 'autogenerated', dirName: 'core/testing'}],
            },
          ],
        },
        {
          type: 'category',
          label: 'Explanations',
          items: [{type: 'autogenerated', dirName: 'core/explanations'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'Udon Test Kit',
      link: {type: 'doc', id: 'udon-test-kit/intro'},
      items: [
        {
          type: 'category',
          label: 'Getting started',
          key: 'udon-test-kit-getting-started',
          items: ['udon-test-kit/add-to-your-project', 'udon-test-kit/first-test'],
        },
        {
          type: 'category',
          label: 'How-to guides',
          key: 'udon-test-kit-how-to',
          items: [{type: 'autogenerated', dirName: 'udon-test-kit/how-to'}],
        },
        {
          type: 'category',
          label: 'Reference',
          key: 'udon-test-kit-reference',
          items: [{type: 'autogenerated', dirName: 'udon-test-kit/reference'}],
        },
        {
          type: 'category',
          label: 'Explanations',
          key: 'udon-test-kit-explanations',
          items: [{type: 'autogenerated', dirName: 'udon-test-kit/explanations'}],
        },
      ],
    },
    // Shared by every project, so it sits at the docs root rather than under one project.
    'install-a-package',
  ],
};

export default sidebars;
