import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Each project under docs/<project>/ gets one top-level category here, built from
 * autogenerated subtrees so individual pages never need a sidebar entry of their own.
 * Adding a second project means adding its own top-level category the same way tsvrc's
 * is built below, not relying on blanket autogeneration (see CLAUDE.md's Structure
 * section for why).
 *
 * Each labeled category below wraps a single-folder `autogenerated` subtree: pointing
 * `dirName` straight at a leaf folder returns its files as a flat list with no label of
 * its own, so the folder's `_category_.json` label is repeated here explicitly to give
 * that flat list a heading.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Framework',
      link: {type: 'doc', id: 'tsvrc/intro'},
      items: [
        {
          type: 'category',
          label: 'Getting started',
          items: ['tsvrc/add-to-your-project', 'tsvrc/first-behaviour'],
        },
        {
          type: 'category',
          label: 'How-to guides',
          items: [{type: 'autogenerated', dirName: 'tsvrc/how-to'}],
        },
        {
          type: 'category',
          label: 'Reference',
          items: [
            {
              type: 'category',
              label: 'Core concepts',
              items: [{type: 'autogenerated', dirName: 'tsvrc/core-concepts'}],
            },
            {
              type: 'category',
              label: 'Players & tracking',
              items: [{type: 'autogenerated', dirName: 'tsvrc/players-tracking'}],
            },
            {
              type: 'category',
              label: 'Networking & data',
              items: [{type: 'autogenerated', dirName: 'tsvrc/networking-data'}],
            },
            {
              type: 'category',
              label: 'UI components',
              items: [{type: 'autogenerated', dirName: 'tsvrc/ui-components'}],
            },
            {
              type: 'category',
              label: 'Game flow',
              items: [{type: 'autogenerated', dirName: 'tsvrc/game-flow'}],
            },
            {
              type: 'category',
              label: 'Utilities',
              items: [{type: 'autogenerated', dirName: 'tsvrc/utilities'}],
            },
            {
              type: 'category',
              label: 'Configuring codegen',
              items: [{type: 'autogenerated', dirName: 'tsvrc/codegen-configuring'}],
            },
            {
              type: 'category',
              label: 'Extending the generator',
              items: [{type: 'autogenerated', dirName: 'tsvrc/codegen-internals'}],
            },
            {
              type: 'category',
              label: 'Testing',
              items: [{type: 'autogenerated', dirName: 'tsvrc/testing'}],
            },
          ],
        },
        {
          type: 'category',
          label: 'Explanations',
          items: [{type: 'autogenerated', dirName: 'tsvrc/explanations'}],
        },
      ],
    },
  ],
};

export default sidebars;
